name: Upload Flightlog from Repo

on:
  workflow_dispatch:

jobs:
  upload-flightlog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "npm"

      - name: Install dependencies
        env:
          PUPPETEER_SKIP_DOWNLOAD: "true"
        run: npm install

      - name: Debug directory & CSV
        run: |
          echo "📂 현재 디렉터리: $(pwd)"
          echo "📄 파일 목록:"
          ls -al
          echo "📂 하위 디렉터리에서 my_flightlog.csv 탐색:"
          find . -type f -name "my_flightlog.csv"

      - name: Upload my_flightlog.csv to roster and Google Sheets
        run: node SaveToFlightlog.js
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          FIREBASE_UID: ${{ secrets.FIREBASE_UID }}
          FIRESTORE_ADMIN_UID: ${{ secrets.FIRESTORE_ADMIN_UID }}
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
          USER_ID: ${{ secrets.USER_ID }}











